// 日结活 AI - 职位数据库
// 字段：id, title, company, pay(元/天), payUnit, location, district, duration(小时),
//       skills(技能标签), type(工种), immediate(是否立即可上岗), rating, description, tags
window.JOB_DB = [
  { id: 1, title: "仓库分拣打包员", company: "顺丰速运中转场", pay: 280, payUnit: "元/天", location: "上海浦东新区", district: "浦东", duration: 10, skills: ["分拣","打包","吃苦耐劳","夜班"], type: "仓储物流", immediate: true, rating: 4.6, description: "负责快递包裹的分拣、扫描、打包，夜班有补贴，包夜宵，当天结清。", tags: ["夜班","包吃","日结"] },
  { id: 2, title: "餐饮后厨帮工", company: "海底捞火锅（五角场店）", pay: 220, payUnit: "元/天", location: "上海杨浦区", district: "杨浦", duration: 8, skills: ["餐饮","切配","卫生","手脚麻利"], type: "餐饮服务", immediate: true, rating: 4.3, description: "协助后厨切配、传菜、清洁，餐食免费，当天结算，长期优先。", tags: ["包吃","日结","就近"] },
  { id: 3, title: "同城配送骑手", company: "美团专送", pay: 350, payUnit: "元/天", location: "上海徐汇区", district: "徐汇", duration: 10, skills: ["骑电动车","导航","配送","沟通"], type: "配送外卖", immediate: true, rating: 4.5, description: "自带电动车或提供车辆，按单+保底，日均250-450，当天提现。", tags: ["多劳多得","日结","可兼职"] },
  { id: 4, title: "展会礼仪接待", company: "国家会展中心", pay: 400, payUnit: "元/天", location: "上海青浦区", district: "青浦", duration: 8, skills: ["形象佳","礼仪","沟通","普通话"], type: "活动展会", immediate: false, rating: 4.7, description: "车展/婚博会礼仪接待，要求身高165+，形象气质佳，包餐包车，活动结束结。", tags: ["形象","活动","包餐"] },
  { id: 5, title: "家装小工/力工", company: "居然之家施工队", pay: 320, payUnit: "元/天", location: "上海闵行区", district: "闵行", duration: 9, skills: ["搬运","体力","装修","听从指挥"], type: "装修建筑", immediate: true, rating: 4.2, description: "协助师傅搬运材料、清理现场、打杂，管午饭，日结现金。", tags: ["体力","包吃","日结现金"] },
  { id: 6, title: "家教辅导（小学数学）", company: "学而思兼职", pay: 300, payUnit: "元/2小时", location: "上海静安区", district: "静安", duration: 2, skills: ["数学","家教","耐心","大学生优先"], type: "教育培训", immediate: false, rating: 4.8, description: "辅导小学3-6年级数学，每周2-3次，每次2小时，按次结算。", tags: ["知识变现","灵活","按次结"] },
  { id: 7, title: "地推扫码员", company: "支付宝推广", pay: 260, payUnit: "元/天", location: "上海黄浦区", district: "黄浦", duration: 8, skills: ["沟通","地推","扫码","外向"], type: "推广销售", immediate: true, rating: 4.0, description: "商圈地推引导用户扫码注册，底薪+提成，日结，多劳多得。", tags: ["提成","日结","户外"] },
  { id: 8, title: "群演/特约演员", company: "横店影视城上海分部", pay: 180, payUnit: "元/天", location: "上海松江区", district: "松江", duration: 12, skills: ["表演","服从安排","守时"], type: "影视演出", immediate: false, rating: 4.1, description: "广告/短剧群演，包盒饭，超时补贴，演完即结。", tags: ["群演","包盒饭","超时补贴"] },
  { id: 9, title: "快递驿站分拣", company: "菜鸟驿站", pay: 200, payUnit: "元/天", location: "上海普陀区", district: "普陀", duration: 8, skills: ["分拣","扫码","细心","体力"], type: "仓储物流", immediate: true, rating: 4.2, description: "快递入库、上架、出库扫码，工作简单，当天结。", tags: ["简单","日结","白班"] },
  { id: 10, title: "IT 兼职开发（前端）", company: "互联网初创团队", pay: 600, payUnit: "元/天", location: "远程/上海", district: "远程", duration: 8, skills: ["Vue","React","JavaScript","前端开发"], type: "IT互联网", immediate: false, rating: 4.9, description: "远程协助开发后台管理页面，按天或按需求结算，技术栈 Vue/React。", tags: ["远程","高薪资","技术"] },
  { id: 11, title: "平面设计兼职", company: "电商设计工作室", pay: 350, payUnit: "元/天", location: "远程", district: "远程", duration: 8, skills: ["PS","设计","电商","审美"], type: "设计创意", immediate: false, rating: 4.7, description: "制作电商主图、详情页，按稿或按天结算，需要作品集。", tags: ["远程","设计","按稿结"] },
  { id: 12, title: "家政保洁钟点工", company: "天鹅到家", pay: 180, payUnit: "元/4小时", location: "上海长宁区", district: "长宁", duration: 4, skills: ["保洁","细心","家务","守时"], type: "家政服务", immediate: true, rating: 4.4, description: "家庭日常保洁，4小时一单，工具自备或提供，按单结算。", tags: ["钟点工","按单结","就近"] },
  { id: 13, title: "代驾司机", company: "滴滴代驾", pay: 300, payUnit: "元/晚", location: "上海全市", district: "全市", duration: 6, skills: ["驾照","代驾","熟悉路况","夜间"], type: "交通出行", immediate: true, rating: 4.5, description: "夜间代驾，按单提成，每晚保底，当晚结算，需3年以上驾龄。", tags: ["夜间","保底","当晚结"] },
  { id: 14, title: "促销导购", company: "苏宁易购门店", pay: 240, payUnit: "元/天", location: "上海虹口区", district: "虹口", duration: 9, skills: ["销售","沟通","促销","产品讲解"], type: "推广销售", immediate: true, rating: 4.1, description: "门店促销导购，底薪+提成，日结，有销售经验优先。", tags: ["提成","日结","门店"] },
  { id: 15, title: "问卷调研/访谈", company: "市场调研公司", pay: 150, payUnit: "元/2小时", location: "上海徐汇区", district: "徐汇", duration: 2, skills: ["问卷","访谈","沟通","认真"], type: "市场调研", immediate: false, rating: 4.3, description: "参与用户访谈或填写问卷，按次结算，轻松简单。", tags: ["轻松","按次结","室内"] },
  { id: 16, title: "摄影/摄像助理", company: "影视工作室", pay: 260, payUnit: "元/天", location: "上海静安区", district: "静安", duration: 10, skills: ["摄影","打灯","器材","细心"], type: "设计创意", immediate: false, rating: 4.4, description: "协助摄影师布光、搬器材、跟焦，包餐，日结，有经验优先。", tags: ["摄影","包餐","日结"] },
  { id: 17, title: "直播场控/助理", company: "MCN 机构", pay: 280, payUnit: "元/天", location: "上海宝山区", district: "宝山", duration: 8, skills: ["直播","场控","互动","电脑操作"], type: "新媒体", immediate: true, rating: 4.2, description: "直播间场控、互动、上下架商品，晚班为主，日结。", tags: ["晚班","直播","日结"] },
  { id: 18, title: "试吃/新品测评", company: "食品品牌", pay: 120, payUnit: "元/次", location: "上海浦东新区", district: "浦东", duration: 1, skills: ["试吃","反馈","表达","守时"], type: "市场调研", immediate: false, rating: 4.0, description: "新品试吃并填写反馈问卷，1小时左右，轻松有趣。", tags: ["轻松","有趣","按次结"] },
  { id: 19, title: "网约车司机（自带车）", company: "滴滴/高德", pay: 500, payUnit: "元/天", location: "上海全市", district: "全市", duration: 12, skills: ["驾照","网约车","服务","熟悉路况"], type: "交通出行", immediate: true, rating: 4.6, description: "自带合规车辆，平台接单，流水当天可提，多劳多得。", tags: ["自带车","流水提现","多劳多得"] },
  { id: 20, title: "活动兼职协助", company: "体育赛事公司", pay: 200, payUnit: "元/天", location: "上海杨浦区", district: "杨浦", duration: 8, skills: ["活动","协助","守时","体力"], type: "活动展会", immediate: true, rating: 4.2, description: "赛事/活动现场协助，签到、引导、物料，包餐，日结。", tags: ["活动","包餐","日结"] },
  { id: 21, title: "文案写作兼职", company: "自媒体团队", pay: 200, payUnit: "元/篇", location: "远程", district: "远程", duration: 4, skills: ["文案","写作","自媒体","中文"], type: "设计创意", immediate: false, rating: 4.5, description: "撰写公众号/小红书文案，按篇结算，需要文字功底。", tags: ["远程","按篇结","写作"] },
  { id: 22, title: "保安（临时）", company: "安保公司", pay: 220, payUnit: "元/天", location: "上海闵行区", district: "闵行", duration: 12, skills: ["保安","值守","责任心","无犯罪记录"], type: "安保物业", immediate: true, rating: 4.0, description: "临时安保值守，12小时两班倒，包餐，日结，需无犯罪记录。", tags: ["值守","包餐","日结"] },
  { id: 23, title: "宠物寄养/遛狗", company: "个人家庭", pay: 120, payUnit: "元/天", location: "上海长宁区", district: "长宁", duration: 1, skills: ["宠物","爱心","耐心","守时"], type: "生活服务", immediate: true, rating: 4.7, description: "上门遛狗或家庭寄养宠物，按天/次结算，喜欢小动物优先。", tags: ["宠物","轻松","就近"] },
  { id: 24, title: "翻译兼职（中英）", company: "翻译公司", pay: 300, payUnit: "元/天", location: "远程", district: "远程", duration: 8, skills: ["英语","翻译","双语","专业"], type: "教育培训", immediate: false, rating: 4.6, description: "中英笔译/口译兼职，按字数或按天结算，需语言证书或经验。", tags: ["远程","语言","按字数结"] }
];
